### ISSUE TITLE
Input to asJSON(keep_vec_names=TRUE) is a named vector. 

### ISSUE THREAD

**Issue by rpc5102** [EducationShinyAppTeam/Hypothesis_Testing#2]
`Using hypothesis as id variables
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.`

Occurs when creating sample plot.

**Comment by xvwang412** [comment]
Hello, I couldn't find this chunk of codes in the app. Can you please point it out to me?

**Comment by rpc5102** [comment]
This may have been thrown by something else. I'll mark this as resolved unless it pops up again.
