### ISSUE TITLE
User Input Enhancement 

### ISSUE THREAD

**Issue by cgray1117** [EducationShinyAppTeam/Hypothesis_Testing#4]
![Screen Shot 2020-05-20 at 10 45 30 AM](https://user-images.githubusercontent.com/64931237/82460414-1f067200-9a87-11ea-9199-4a5b18fe7b83.png)

A slider input with limits (0,1.00) would be more appropriate than a numeric input because a value greater than 1 gives an error for the exact hypothesis test.
Edit: This input is in the hypothesis testing section of the app if it wasn't clear.

**Comment by xvwang412** [comment]
Fixed
