### ISSUE TITLE
Error message revision

### ISSUE THREAD

**Issue by cgray1117** [EducationShinyAppTeam/Hypothesis_Testing#5]
![Screen Shot 2020-05-20 at 11 03 21 AM](https://user-images.githubusercontent.com/64931237/82462419-8cb39d80-9a89-11ea-9428-63d60d42adb5.png)

Here, the app displays an error message because both end of the slider are set to one number. The same error is displayed when 0 is selected. Rather than a general error message, try informing the user that there are no players in the dataset that satisfy that filter, or something to that extent.

**Comment by xvwang412** [comment]
Fixed
